apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-deployment
  labels:
    app: foo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foo-app
  template:
    metadata:
      labels:
        app: foo-app
    spec:
      containers:
        - name: foo-app
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=foo"
          ports:
            - containerPort: 5678
